DSA Add-on Course Week 4 Practice Problems

1. Create a NumPy array of integers from 1 to 10

In [2]:
import numpy as np

In [ ]:
arr1=np.arange(1,11)

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Create a 2x3 NumPy array filled with zeros.


In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

3. Create a NumPy array of even numbers from 2 to 20.

In [ ]:
arr2=np.arange(2,21,2)

In [ ]:
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4. Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2= np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays.

In [ ]:
arr3 = np.array([1, 2, 3])

In [ ]:
arr4 = np.array([4, 5, 6])

In [ ]:
#addition
arr=arr3+arr4
arr

array([5, 7, 9])

In [ ]:
#substraction
arr=arr3-arr4
arr

array([-3, -3, -3])

In [ ]:
#multiplication
arr=arr3*arr4
arr

array([ 4, 10, 18])

In [ ]:
#division
arr=arr3/arr4
arr

array([0.25, 0.4 , 0.5 ])

5. Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.

In [ ]:
arr5=np.random.rand(100)
arr5

array([0.83310979, 0.89653481, 0.77163506, 0.14216938, 0.91187313,
       0.71871255, 0.98863668, 0.76136198, 0.6986404 , 0.89793772,
       0.32953654, 0.35078549, 0.8251056 , 0.88037379, 0.37337619,
       0.22286132, 0.95231106, 0.44451314, 0.0702132 , 0.50385201,
       0.90015143, 0.09972977, 0.6147039 , 0.7778531 , 0.13458852,
       0.88981828, 0.59653344, 0.54596455, 0.48182102, 0.63962625,
       0.16396147, 0.59688227, 0.82757731, 0.88974788, 0.94005681,
       0.43811951, 0.49645853, 0.48390397, 0.62581524, 0.06868792,
       0.52780533, 0.41488744, 0.43614748, 0.72778886, 0.73841315,
       0.54752567, 0.82979936, 0.63265263, 0.44379308, 0.85163915,
       0.91790325, 0.20486062, 0.70632571, 0.74580543, 0.2408028 ,
       0.42401933, 0.01741721, 0.89988888, 0.13659252, 0.17245981,
       0.9089086 , 0.65809966, 0.88552919, 0.09498243, 0.70016041,
       0.02505848, 0.2411079 , 0.31677781, 0.11151318, 0.41252554,
       0.52394199, 0.76384461, 0.51474102, 0.26893671, 0.09693

In [ ]:
#mean
arr5.mean()

0.4980348136551658

6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4).

In [ ]:
arr6=np.random.randint(0,20,12)
arr6


array([18, 15,  7, 14,  2,  4,  9, 13, 15,  7, 14, 19])

In [ ]:
arr6=np.random.randint(0,20,12).reshape(3,4)
arr6

array([[ 6,  5, 19,  5],
       [19,  1, 18, 11],
       [ 0, 16,  0, 10]])

7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions.


In [ ]:
arr7=np.array([1,2,3,4,5])
np.square(arr7)

array([ 1,  4,  9, 16, 25])

8. Create a 5x5 identity matrix using NumPy

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9. Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6])

In [ ]:
 a = np.array([1, 2, 3])

In [ ]:
b = np.array([4, 5, 6])

In [ ]:
a.dot(b)

32

10.Find the index of the maximum value and the index of the minimum value
in a NumPy array.

In [ ]:
arr8=np.arange(1,50,2)
arr8

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [ ]:
# index maximum value
arr8.argmax()

24

In [ ]:
#index minimum value
arr8.argmin()

0

11.Concatenate two random NumPy arrays horizontally and vertically

In [3]:
a=np.zeros((4,4))
b=np.ones((4,4))
c=np.concatenate((a,b))
d=np.concatenate((a,b),axis=1)
print('vertical concatenation-\n',c)
print('horizontal concatenation-\n',d)

vertical concatenation-
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
horizontal concatenation-
 [[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


12.Given a 2D NumPy array, calculate the sum of each row and each column
separately.

In [4]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print('sum of each column is', np.sum(arr,axis=0))
print('sum of each rowis ',np.sum(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sum of each column is [28 32 36 40]
sum of each rowis  [10 26 42 58]


13.Find the common elements between two NumPy arrays.

In [5]:
a=np.array([[4,9],[5,8],[1,7]])
b=np.array([[3,9],[5,2],[6,7]])
c=np.intersect1d(a,b)
print("the common elements between a and b are ",c)

the common elements between a and b are  [5 7 9]


14.Replace all negative values in a NumPy array with zeros.

In [6]:
x=np.array([1,2,3,-4,-5,-6])
x[x<0]=0
x

array([1, 2, 3, 0, 0, 0])

15.Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order.

In [7]:
arr1=np.random.randint(1,101,100)
arr1.sort()
arr1

array([  4,   5,   6,   6,   7,   8,   8,   9,  10,  12,  13,  14,  14,
        15,  16,  16,  17,  18,  18,  19,  20,  21,  21,  22,  23,  23,
        24,  25,  25,  27,  27,  27,  28,  30,  31,  41,  44,  45,  46,
        47,  48,  48,  49,  49,  50,  50,  51,  52,  52,  52,  53,  56,
        57,  59,  60,  60,  61,  62,  63,  64,  66,  66,  68,  70,  70,
        71,  71,  73,  74,  75,  75,  75,  76,  76,  76,  76,  77,  78,
        79,  79,  81,  82,  82,  85,  85,  85,  86,  87,  89,  89,  89,
        89,  90,  91,  92,  93,  93,  97, 100, 100])

16.Calculate the element-wise absolute difference between two NumPy
arrays.

In [8]:
a=np.array([1,2,3,4,5])
b=np.array([6,8,10,12,14])
c=np.absolute(a-b)
print("The element wise absolute differences between the two arrays is",c)

The element wise absolute differences between the two arrays is [5 6 7 8 9]


17.Given a 2D NumPy array, extract the first row and the last column.


In [13]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
firstrow=arr[0]
lastcol=arr[:,[-1]]
print("firstrow is \n",firstrow)
print("last column is \n",lastcol)

firstrow is 
 [1 2 3]
last column is 
 [[3]
 [6]
 [9]]


18.Slice a 1D NumPy array to get every other element.

In [14]:
a=np.array([1,2,3,4,5])
x=a[0:len(a)+1]
print(x)

[1 2 3 4 5]


19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements.

In [15]:
arr=np.array([[10,1,14,16,18,20],[22,24,26,28,30,32],[34,36,38,40,42,44],[46,48,50,52,54,56],[58,60,62,64,66,68],[70,72,74,76,78,80]])
x=arr[2:4,[2,3]]
print('original array is \n',arr)
print('central 2x2 elements include\n',x)

original array is 
 [[10  1 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]
central 2x2 elements include
 [[38 40]
 [50 52]]


20.Reverse a 1D NumPy array using slicing.

In [16]:
a=np.array([1,2,3,4,5])
x=a[::-1]
x

array([5, 4, 3, 2, 1])